### ISSUE TITLE
Problem with ConfirmSignup

### ISSUE THREAD

**Issue by stand00d** [kdgregory/example-cognito-java#1]
I am getting errors when trying to confirm new users with a Lambda modeled after the ConfirmSignup servlet.
 
One difference in my app, I am using separate values for email and username.

In one case, when I call the lambda as written, it passes the adminInitiateAuth but when I call adminRespondToAuthChallenge I get:

Invalid attributes given, preferred_username is missing (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: 5190483b-402f-11e7-a94f-71b61392af0f)

In the other case, when I call adminRespond... with the username modifed to be "preferred_username:myusername" I get:

Invalid session provided for the user. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: d16ddd7f-4032-11e7-876f-d93bbe12b132)

Oh, and I am using 

AWSCognitoIdentityProvider cognitoClient = AWSCognitoIdentityProviderClientBuilder.defaultClient();

instead of the client as declared in AbstractServlet.

Any help would be appreciated...

**Comment by kdgregory** [comment]
Sorry, I didn't see this until just now. Hopefully you got the problem worked out. Without seeing exactly what you're doing, my best guess is that you need to provide two parameters to the challenge response.
